!> TPLS FRUIT unit test framework driver.
!!
!! @author Prashant Valluri, Lennon O Naraigh, Iain Bethune, David
!! Scott, Peter Spelt, Mike Jackson. Based on driver code
!! auto-generated by FRUIT's Ruby pre-processor.
!! @version $Revision: 299 $
!! @copyright (c) 2013-2014, Prashant Valluri, Lennon O Naraigh, 
!! Iain Bethune, David Scott, Peter Spelt, The University of
!! Edinburgh, all rights reserved.
!! This program is distributed under the BSD License See LICENSE.txt
!! for details.

program tpls_test_driver
  use fruit

  ! Add TPLS modules here...
  use grid_utils_test
  use options_utils_test
  use tpls_io_test

  call init_fruit()
  call init_fruit_xml()

  ! Add TPLS module basket calls here..
  call grid_utils_basket()
  call options_utils_basket()
  call tpls_io_basket()

  call fruit_summary()
  call fruit_summary_xml()
  call fruit_finalize()

end program tpls_test_driver
