!> TPLS FRUIT unit test framework utilities.
!!
!! @author Prashant Valluri, Lennon O Naraigh, Iain Bethune, David
!! Scott, Peter Spelt, Mike Jackson. Based on driver code
!! auto-generated by FRUIT's Ruby pre-processor.
!! @version $Revision: 201 $
!! @copyright (c) 2013-2014, Prashant Valluri, Lennon O Naraigh, 
!! Iain Bethune, David Scott, Peter Spelt, The University of
!! Edinburgh, all rights reserved.
!! This program is distributed under the BSD License See LICENSE.txt
!! for details.

module tpls_fruit_utils
  use fruit
  implicit none
contains

  !> Invoke a test case sub-routine of a test suite, invoking the
  !! suite's setup sub-routine first, and its teardown sub-routine
  !! after. This sub-routine was abstracted out from "basket" code
  !! auto-generated by FRUIT's Ruby pre-processor.
  subroutine run_fruit_test_case(test_case,test_case_name, &
    setup,teardown,test_suite_name)
    interface
      subroutine test_case()
      end subroutine
    end interface
    character(*),intent(in) :: test_case_name
    interface
      subroutine setup()
      end subroutine
    end interface
    interface
      subroutine teardown()
      end subroutine
    end interface
    character(*),intent(in) :: test_suite_name

    call setup()
    write(*,'(/A,A,A,A)') 'Running: ',test_suite_name,':',test_case_name
    call set_unit_name(test_case_name)
    call run_test_case(test_case,test_case_name)
    if (.not. is_case_passed()) then
      call case_failed_xml(test_case_name,test_suite_name)
    else
      call case_passed_xml(test_case_name,test_suite_name)
    end if
    call teardown()
  end subroutine run_fruit_test_case

end module tpls_fruit_utils
